# Copyright (c) 2024 vesoft inc. All rights reserved.

name: snapshot

on:
  push:
    branches: [ dev ]


jobs:
  deploy-java-driver-snapshot:
    runs-on: [ self-hosted, linux ]
    steps:
      - name: Clean runner
        uses: webiny/action-post-run@3.1.0
        with:
          run: find . -mindepth 1 -delete

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: install nebula
        run: |
          docker compose pull && docker compose up -d
          sleep 60
        working-directory: docker-compose

      - name: package flink connector
        run: |
          mvn clean package

      - name: setup minio
        uses: vesoft-inc/.github/actions/setup-minio@master
        with:
          minio_url: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET }}

      - name: Copy java sdk to release on MinIO
        run: |      
          mc cp target/nebula-flink-connector-5.0-SNAPSHOT.jar minio/nightly-build/nebula-ng-flinkconnector/
        working-directory: connector

      - name: stop nebula
        if: always()
        run: |
          docker compose down
        working-directory: docker-compose
